export const columsTablePopsa = [
  {
    field: "CODIGO_DATOS_POPSA",
    headerName: "ID",
    hideInModal: true,
    customHeaderExcel: "ID",
    exportable: true,
  },
  {
    field: "CODIGO_DATOS_SPANCOP",
    headerName: "ID SNAPCOP",
    hideInModal: true,
    hideInTable: true,
  },
  {
    field: "EMPRESA",
    headerName: "Nombre Cliente",
    type: "text",
    disabled: true,
    filterable: true,
    customHeaderExcel: "Empresa",
    exportable: true,
  },
  {
    field: "USUARIO",
    headerName: "Vendedor",
    type: "text",
    disabled: true,
    hideInTable: true,
    customHeaderExcel: "Vendedor",
    exportable: true,
  },
  {
    field: "FECHA_PROPUESTA",
    headerName: "Fecha Propuesta",
    type: "date",
    dateFormat: "dd/MM/yyyy",
    exportable: true,
  },
  {
    field: "PROPOSITO",
    headerName: "Propósito - ¿Por qué hace la visita?",
    type: "textarea",
    hideInTable: true,
    exportable: true,
  },
  {
    field: "OBJETIVO",
    headerName: "Objetivo - ¿Qué resultados espera obtener de la visita?",
    type: "textarea",
    hideInTable: true,
    exportable: true,
  },
  {
    field: "PREMISA",
    headerName: "Premisa - ¿Qué sabe sobre el cliente?",
    type: "textarea",
    hideInTable: true,
    exportable: true,
  },
  {
    field: "ESTRATEGIA",
    headerName: "Su Estrategia - ¿Cómo va a conseguir el objetivo?",
    type: "textarea",
    hideInTable: true,
    exportable: true,
  },
  {
    field: "ANTICIPACION",
    headerName: "Anticipación - ¿Qué prodría preguntar el cliente?",
    type: "textarea",
    hideInTable: true,
    exportable: true,
  },
  {
    field: "CODIGO_CALL_REPORT",
    headerName: "Call Report",
    type: "checkbox",
    hideInModal: true,
  },
];
