export const columnsSPANCOPdef = [
  {
    field: "CODIGO_DATOS_SPANCOP",
    headerName: "ID",
    align: "left",
    filterable: false,
    sortable: false,
    minWidth: 20,
    sx: { backgroundColor: "#f5f5f5", fontWeight: "bold" },
    hideInModal: true,
    exportable: true,
  },
  {
    field: "ESTADO_FINAL",
    headerName: "Estado",
    type: "dropdown",
    minWidth: 80,
    filterable: true,
    hideInModal: true,
    exportable: true,
    disabled: true,
  },
  {
    field: "DISTRIBUIDOR",
    headerName: "Distribuidor",
    type: "text",
    minWidth: 80,
    filterable: true,
    hideInTable: true,
    exportable: true,
    disabled: true,
  },
  {
    field: "CEDULA_VENTA",
    headerName: "Cédula de Venta",
    type: "dropdown",
    minWidth: 100,
    filterable: true,
    exportable: true,
  },
  {
    field: "EMPRESA",
    headerName: "Empresa",
    type: "dropdown-add",
    minWidth: 100,
    filterable: true,
    options: [],
    exportable: true,
  },
  {
    field: "VENDEDOR",
    headerName: "Vendedor",
    type: "text",
    minWidth: 100,
    filterable: true,
    exportable: true,
    disabled: true,
  },

  {
    field: "ID_VENDEDOR",
    headerName: "Id Vendedor",
    type: "text",
    minWidth: 100,
    hideInTable: true,
    hideInModal: true,
    disabled: true,
  },
  {
    field: "CLIENTE_EXISTE",
    headerName: "¿Cliente existe?",
    type: "checkbox",
    minWidth: 20,
    filterable: true,
    exportable: true,
    defaultValue: false,
  },
  {
    field: "TIPO_NEGOCIO",
    headerName: "Tipo Negocio",
    type: "dropdown",
    minWidth: 100,
    filterable: true,
    exportable: true,
  },
  {
    field: "GRUPO_PRODUCTO",
    headerName: "Grupo Producto",
    type: "dropdown",
    minWidth: 150,
    filterable: true,
    exportable: true,
  },
  {
    field: "SECTOR",
    headerName: "Sector",
    type: "dropdown",
    minWidth: 120,
    filterable: true,
    exportable: true,
  },
  {
    field: "SEGMENTO",
    headerName: "Segmento",
    type: "dropdown",
    minWidth: 120,
    filterable: true,
    exportable: true,
  },
  {
    field: "TIPO_OPORTUNIDAD",
    headerName: "Tipo Oportunidad",
    type: "dropdown",
    minWidth: 120,
    filterable: true,
    exportable: true,
  },
  {
    field: "FECHA_ESTIMADA_PRIMER_PEDIDO",
    headerName: "Fecha Estimada 1er pedido",
    type: "date",
    dateFormat: "MM/yyyy",
    minWidth: 120,
    filterable: true,
    exportable: true,
  },
  {
    field: "RAZONES_CLAVE",
    headerName: "Razones Clave Para Ganar el Negocio (o por que lo perdio)",
    type: "textarea",
    minWidth: 200,
    filterable: true,
    exportable: true,
  },
  {
    field: "PROBABILIDAD_EXITO",
    headerName: "Probabilidad de Éxito",
    type: "dropdown",
    minWidth: 120,
    filterable: true,
    exportable: true,
  },
  {
    field: "ESTIMACION_VOLUMEN_ANUAL",
    headerName: "Estimacion Volumen Anual (litros)",
    type: "float",
    minWidth: 120,
    filterable: true,
    exportable: true,
  },
  {
    field: "VOLUMEN_PREVISTO",
    headerName: "Volumen Previsto 2025",
    type: "float",
    minWidth: 120,
    filterable: true,
    exportable: true,
  },
  {
    field: "VOLUMEN_REAL",
    headerName: "Volumen Real 2025",
    type: "float",
    minWidth: 120,
    filterable: true,
    exportable: true,
  },
  {
    field: "FECHA_S",
    headerName: "S - Sospechoso Fecha",
    type: "date",
    dateFormat: "dd/MM/yyyy",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    disableIfFilled: (data) => !!data.FECHA_S,
    exportable: true,
  },
  {
    field: "OBSERVACION_S",
    headerName: "S - Sospechoso Observación",
    type: "textarea",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    disableIfFilled: (data) => !!data.OBSERVACION_S,
    exportable: true,
  },
  {
    field: "FECHA_P_INICIAL",
    headerName: "P - Prospecto Fecha",
    type: "date",
    dateFormat: "dd/MM/yyyy",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_S,
    disableIfFilled: (data) => !!data.FECHA_P_INICIAL,
    exportable: true,
  },
  {
    field: "OBSERVACION_P",
    headerName: "P - Prospecto Observación",
    type: "textarea",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_S,
    disableIfFilled: (data) => !!data.OBSERVACION_P,
    exportable: true,
  },
  {
    field: "FECHA_A",
    headerName: "A - Análisis y construcción de relaciones Fecha",
    type: "date",
    dateFormat: "dd/MM/yyyy",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_P_INICIAL,
    disableIfFilled: (data) => !!data.FECHA_A,
    exportable: true,
  },
  {
    field: "OBSERVACION_A",
    headerName: "A - Análisis y construcción de relaciones Observación",
    type: "textarea",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_P_INICIAL,
    disableIfFilled: (data) => !!data.OBSERVACION_A,
    exportable: true,
  },
  {
    field: "FECHA_N",
    headerName: "N - Propuesta Fecha",
    type: "date",
    dateFormat: "dd/MM/yyyy",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_A,
    disableIfFilled: (data) => !!data.FECHA_N,
    exportable: true,
  },
  {
    field: "OBSERVACION_N",
    headerName: "N - Propuesta Observación",
    type: "textarea",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_A,
    disableIfFilled: (data) => !!data.OBSERVACION_N,
    exportable: true,
  },
  {
    field: "FECHA_C",
    headerName: "C - Contrato Fecha",
    type: "date",
    dateFormat: "dd/MM/yyyy",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_N,
    disableIfFilled: (data) => !!data.FECHA_C,
    exportable: true,
  },
  {
    field: "OBSERVACION_C",
    headerName: "C - Contrato Observación",
    type: "textarea",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_N,
    disableIfFilled: (data) => !!data.OBSERVACION_C,
    exportable: true,
  },
  {
    field: "FECHA_O",
    headerName: "O - Orden Fecha",
    type: "date",
    dateFormat: "dd/MM/yyyy",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_C,
    disableIfFilled: (data) => !!data.FECHA_O,
    exportable: true,
  },
  {
    field: "OBSERVACION_O",
    headerName: "O - Orden Observación",
    type: "textarea",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_C,
    disableIfFilled: (data) => !!data.OBSERVACION_O,
    exportable: true,
  },
  {
    field: "FECHA_P_FINAL",
    headerName: "P - Pago Fecha",
    type: "date",
    dateFormat: "dd/MM/yyyy",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_O,
    disableIfFilled: (data) => !!data.FECHA_P_FINAL,
    exportable: true,
  },
  {
    field: "OBSERVACION_P_FINAL",
    headerName: "P - Pago Observación",
    type: "textarea",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    shouldDisplay: (data) => !!data.FECHA_O,
    disableIfFilled: (data) => !!data.OBSERVACION_P_FINAL,
    exportable: true,
  },
  {
    field: "NOTAS",
    headerName: "Notas / Comentarios",
    type: "textarea",
    minWidth: 120,
    filterable: true,
    hideInTable: true,
    exportable: true,
  },
  {
    field: "TOP5",
    headerName: "Big5 Top5",
    type: "text",
    disabled: true,
    minWidth: 120,
    filterable: true,
    exportable: true,
  },
];

export const columsPopsadef = [
  {
    field: "CODIGO_DATOS_POPSA",
    headerName: "ID",
    hideInModal: true,
  },
  {
    field: "CODIGO_DATOS_SPANCOP",
    headerName: "ID SNAPCOP",
    hideInModal: true,
  },
  {
    field: "EMPRESA",
    headerName: "Nombre Cliente",
    type: "text",
    disabled: true,
    exportable: true,
  },
  {
    field: "USUARIO",
    headerName: "Vendedor",
    type: "text",
    disabled: true,
    exportable: true,
  },
  {
    field: "FECHA_PROPUESTA",
    headerName: "Fecha Propuesta",
    type: "date",
    dateFormat: "dd/MM/yyyy",
    exportable: true,
  },
  {
    field: "PROPOSITO",
    headerName: "Propósito - ¿Por qué hace la visita?",
    type: "textarea",
    exportable: true,
  },
  {
    field: "OBJETIVO",
    headerName: "Objetivo - ¿Qué resultados espera obtener de la visita?",
    type: "textarea",
    exportable: true,
  },
  {
    field: "PREMISA",
    headerName: "Premisa - ¿Qué sabe sobre el cliente?",
    type: "textarea",
    exportable: true,
  },
  {
    field: "ESTRATEGIA",
    headerName: "Su Estrategia - ¿Cómo va a conseguir el objetivo?",
    type: "textarea",
    exportable: true,
  },
  {
    field: "ANTICIPACION",
    headerName: "Anticipación - ¿Qué prodría preguntar el cliente?",
    type: "textarea",
    exportable: true,
  },
];

export const columsCallReportdef = [
  {
    field: "CODIGO_CALL_REPORT",
    headerName: "ID",
    hideInModal: true,
  },
  {
    field: "CLIENTE",
    headerName: "Cliente",
    type: "text",
    disabled: true,
    exportable: true,
  },
  {
    field: "FECHA",
    headerName: "Fecha",
    type: "date",
    dateFormat: "dd/MM/yyyy",
    disabled: true,
    exportable: true,
  },
  {
    field: "PARTICIPANTES",
    headerName: "Participantes",
    type: "textarea",
    exportable: true,
  },
  {
    field: "OBJETIVO_PREVIO",
    headerName: "Objetivo Previo",
    type: "textarea",
    disabled: true,
    exportable: true,
  },
  {
    field: "OBJETIVO_VISITA",
    headerName: "",
    type: "textarea",
    exportable: true,
  },
  {
    field: "DISCUSION",
    headerName: "Lo que se discutió",
    type: "textarea",
    exportable: true,
  },
  {
    field: "ACCIONES",
    headerName: "Acciones (¿Qué?, ¿Quién? y ¿Cuándo?)",
    type: "list",
    exportable: true,
    listConfig: {
      idField: "CODIGO_ACCIONES_CALL_REPORT",
      textField: "ACCION",
      checkedField: "REALIZADA",
      newItemIdField: "CODIGO_ACCIONES_CALL_REPORT",
    },
    listLabels: {
      addButton: "Añadir",
      newItemPlaceholder: "Nueva acción",
    },
    // Configuración declarativa para el formato en PDF
    listItemFormatter: {
      textField: "ACCION",
      checkedField: "REALIZADA",
      // Si quieres numeración automática, omite esta propiedad
      // index: "CODIGO_ACCIONES_CALL_REPORT"  // Para usar un campo específico como numeración
    },
  },
  {
    field: "INFORMACION_UTIL",
    headerName: "Otra Información Útil",
    type: "textarea",
    exportable: true,
  },
];
export const columsObservacionesdef = [
  {
    field: "CODIGO_OBSERVACIONES",
    headerName: "ID",
    hideInModal: true,
  },
  {
    field: "CODIGO_DATOS_SPANCOP",
    headerName: "ID_SPACOP",
    hideInModal: true,
  },
  {
    field: "FECHA",
    headerName: "Fecha de la observación",
    type: "date",
    dateFormat: "dd/MM/yyyy",
    disableIfFilled: (data) => !!data.FECHA,
  },
  {
    field: "TITULO",
    headerName: "Título",
    type: "text",
  },
  {
    field: "OBSERVACION",
    headerName: "Observación",
    type: "textarea",
  },
];
